### PR TITLE
Burgerfix

### PR DESCRIPTION
**Pull request by haxybaxy**
added the svg icon for the burger, @jose-izarra do ur thang 

### Summary by CodeRabbit

**Release Notes**

- **Style**: Updated the layout and spacing of elements in the footer for better visual organization.
- **Chore**: Removed unused code from the NavBar component, improving code cleanliness.
- **Style**: Enhanced the NavBar's visual appeal by updating the burger icon, background color, and color of social links and list items.
- **Style**: Adjusted the styling of the main body element on the index page for a cleaner look.
- **Refactor**: Simplified the AboutInfo component by removing the SidewaysHeader component and directly including content.
- **Style**: Improved the SidewaysHeader component's responsiveness by adjusting the media query, ensuring a better user experience on various screen sizes.
- **Refactor**: Reorganized components on the index page for a more intuitive user interface.

### CODE REVIEW

**Comment by haxybaxy** [comment]
also if u decide to implement it with the svg tag, here is the d value:
`d="M2319.4,5114.7c-729-37-1305-252-1675-626 c-258-262-366-506-370-839c-1-129,0-144,22-188c27-56,78-108,127-132l34-16v-74v-73l-53,14c-28,7-79,14-113,14c-50,0-64-4-81-22 c-30-34-34-55-18-94s36-49,122-57c35-4,80-15,100-24l38-18v-120v-120l-95-5c-115-7-183-34-250-102c-135-135-144-351-20-492 c35-39,113-92,151-101c26-6,27-10,33-103c9-122,36-206,90-280c67-90,142-142,251-173c75-21,3815-21,3890,0c109,31,184,83,251,173 c54,74,81,158,90,280c6,93,7,97,33,103c38,9,116,62,151,101c124,141,115,357-20,492c-67,68-135,95-250,102l-95,5l-3,121l-3,121 l44,17c23,9,75,20,114,25c85,11,91,14,109,57c16,38,8,68-25,98c-18,16-31,18-98,13c-43-4-93-9-110-13l-33-6v70c0,71,0,71,34,87 c49,24,100,76,127,132c22,44,23,59,22,188c-4,331-112,576-365,833c-269,272-619,451-1088,555 C3088.4,5104.7,2689.4,5132.7,2319.4,5114.7z M3027.4,4925.7c200-30,285-45,399-73c475-114,850-347,1072-663 c124-176,169-320,169-536c0-120,0-121-29-150l-29-29h-2052h-2052l-29,29c-29,29-29,30-29,150c0,271,86,470,300,695 c321,337,789,523,1485,590C2315.4,4946.7,2955.4,4935.7,3027.4,4925.7z M4487.4,3190.7c0-108-1-114-23-129c-39-25-127-47-192-47 c-82,0-145,20-232,74c-40,24-103,57-140,73c-63,26-78,28-198,28c-117-1-137-3-196-27c-37-14-97-45-134-69c-86-54-161-79-240-79 c-84,0-138,18-256,86c-123,70-205,94-319,94s-196-24-319-94c-118-68-172-86-256-86c-82,0-145,20-232,74c-40,24-103,57-140,73 c-63,26-78,28-198,28c-117-1-137-3-196-27c-37-14-97-45-134-69c-123-77-238-98-355-63c-100,30-100,30-100,160v114h1930h1930V3190.7z M1567.4,2991.7c30-14,91-47,134-71c108-61,191-80,314-73c117,6,182,27,298,98c181,109,314,106,503-10c106-64,161-82,283-88 c120-7,206,12,303,68c150,85,194,102,270,107c100,6,153-9,275-79c58-33,128-67,155-76c75-24,226-28,308-9c38,9,70,16,73,16 c2,0,4-31,4-70v-70h-1930h-1930v70c0,39,3,70,8,70c4-1,34-7,67-15c79-19,202-19,278,1c66,17,111,38,200,92c94,57,149,73,247,69 C1494.4,3019.7,1524.4,3012.7,1567.4,2991.7z M1990.4,2550.7c63-26,117-111,117-184c0-35,43-72,82-72c84,1,108,75,64,203l-23,67 h1284c1056,0,1289-2,1316-14c43-18,93-76,108-127c10-32,10-51,1-85c-17-63-38-91-91-122l-46-27l-737-3c-406-1-738-1-738,2 c0,2,9,25,20,51c26,62,35,143,18,175c-18,34-58,55-91,46c-39-10-64-41-71-93c-9-65-46-124-98-153l-43-25h-1375h-1375l-46,27 c-53,31-74,59-91,122c-9,34-9,53,1,85c14,49,64,109,106,127C327.4,2570.7,1943.4,2570.7,1990.4,2550.7z M4665.4,1927.7 c-2-61-10-100-23-128c-23-47-81-107-127-132c-31-17-122-18-1958-18s-1927,1-1958,18c-46,25-104,85-127,132c-13,28-21,67-23,128 l-4,87h2112h2112L4665.4,1927.7z M2411.4,4730.7c-21-18-28-32-28-61c0-33,8-45,71-106c78-76,109-86,155-49c55,43,40,98-51,183 C2487.4,4762.7,2456.4,4769.7,2411.4,4730.7z M3148.4,4678.7c-39-33-43-83-8-118c25-25,177-66,243-66c72,0,109,80,62,135 c-19,21-44,31-133,50c-60,13-115,24-122,25C3184.4,4704.7,3165.4,4692.7,3148.4,4678.7z M1701.4,4564.7c-40-16-54-49-54-127 c0-91,23-125,85-125c30,0,45,6,62,27c19,22,23,37,23,100c0,62-3,78-22,99C1769.4,4567.7,1732.4,4577.7,1701.4,4564.7z M3712.4,4522.7c-31-18-44-40-45-76c0-42,28-71,111-113c198-99,397-285,476-444c11-22,28-72,37-112c10-40,26-79,37-89 c29-26,83-23,114,6c30,28,32,68,10,155c-60,228-297,482-598,639C3762.4,4536.7,3744.4,4541.7,3712.4,4522.7z M2961.4,4270.7 c-21-18-28-32-28-61c0-33,8-45,71-106c73-71,100-82,144-58c30,16,49,67,37,100c-5,15-38,54-73,88 C3040.4,4303.7,3007.4,4311.7,2961.4,4270.7z M2232.4,4186.7c-17-11-52-43-78-72c-37-41-47-60-47-87c0-47,37-83,86-83 c31,0,45,9,105,69c72,72,81,94,58,144c-12,26-47,47-77,47C2270.4,4204.7,2248.4,4196.7,2232.4,4186.7z M1242.4,4105.7 c-11-5-48-38-82-74c-72-74-80-106-38-151c18-19,34-26,61-26c33,0,46,8,106,68c58,58,68,74,68,103 C1356.4,4090.7,1300.4,4128.7,1242.4,4105.7z M3622.4,4010.7c-38-18-121-103-134-139c-15-40,8-94,46-104c48-12,66-4,136,65 c59,59,67,71,67,104c0,36-26,78-49,78c-5,0-15,2-23,5C3658.4,4021.7,3639.4,4017.7,3622.4,4010.7z M1700.4,3919.7 c-36-15-53-42-53-81c0-19,18-45,69-97c60-62,74-71,105-71c48,0,86,36,86,82c0,28-11,45-61,97 C1775.4,3923.7,1745.4,3938.7,1700.4,3919.7z M2682.4,3809.7c-34-33-34-83,1-116c23-21,35-24,106-24c75,0,81,2,104,28 c31,37,31,81-1,112c-22,22-32,25-105,25S2704.4,3831.7,2682.4,3809.7z"
`

**Comment by jose-izarra** [comment]
> added the svg icon for the burger, @jose-izarra do ur thang
> 
> ### Summary by CodeRabbit
> * Style: Updated the layout and spacing of the Footer component for better visual organization.
> * Chore: Removed unused code from the NavBar component, improving code cleanliness.
> * New Feature: Enhanced the NavBar component with a new SVG burger icon and updated color schemes for improved user experience.
> * Style: Adjusted the styling of the main body on the index page for a cleaner look and feel.
> 
> These changes aim to improve the overall user interface, making it more visually appealing and user-friendly.

I

**Comment by jose-izarra** [comment]
I added the svg and made navbar a bit cleaner in dark mode. I did my thing @haxybaxy.

**Comment by jose-izarra** [comment]
@velocitatem I think this is ready for merge

**Comment by haxybaxy** [comment]
@jose-izarra 😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻

**Comment by velocitatem** [comment]
@jose-izarra 🤔❓👨‍🍳🍳

**Pull request merged**
